package theBank.transactions;

public enum TType {
	ACH_CREDIT("ACH CREDIT"),
	ACH_WITHDRAWL("ACH WITHDRAWL"),
	ACH_COLLECTIONS ("ACH COLLECTIONS"),
	ACH_PAYMENTS ("ACH PAYMENTS"),
	CHECK ("CHECK"),
	DEBIT_CARD_PURCHASE("DEBIT CARD PURCHASE"),
	CASH_WITHDRAWL("CASH WITHDRAWL"),
	CASH_DEPOSIT("CASH DEPOSIT"),
	INTEREST("INTEREST"),
	INVALID("INVALID"),
	OVERDRAFT("OVERDRAFT"),
	POS_PURCHASE("POS PURCHASE"),
	POS_CREDIT("POS CREDIT/ADJ POS DEPOSIT"),
	NETWORK_POS_PURCHASE("NETWORK POS PURCHASE"),
	CHARGE_BACK("CHARGE BACK"),
	REFUND("REFUND"),
	TRANSFER("TRANSFER"),
	MERCHANT_CAPTURE_DEPOSIT("MERCHANT CAPTURE DEPOSIT");
	private final String value;
	private TType(String value) {
		this.value = value;
	}
	
	public String toString() {
		return this.value;
	}
}
